name: Rust tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    # run this gha if...
    paths:
      # changes to Rust code
      - 'src/**'
      # changes to this gha
      - '.github/workflows/rust-tests.yaml'
      # changes to the Rust dependencies/metadata/other project toml datas
      - 'Cargo.toml'
      
jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features # -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run --lib